# Generated by Django 4.2.27 on 2025-12-11 23:58

import apps.cards.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit Card')], default='DEBIT', max_length=10)),
                ('card_number', models.CharField(default=apps.cards.models.generate_card_number, max_length=16, unique=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cards', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.bankaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'APPROVED')), fields=('bank_account',), name='unique_active_card_per_account'),
        ),
    ]
