# Generated by Django 4.2.27 on 2025-12-11 23:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('EUR', 'Euro')], default='EUR', max_length=3)),
                ('description', models.CharField(max_length=255)),
                ('reference_iban', models.CharField(blank=True, max_length=34)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('idempotency_key', models.CharField(max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.bankaccount')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transactions', to='transactions.transaction')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bank_account', '-created_at'], name='transaction_bank_ac_790308_idx'), models.Index(fields=['idempotency_key'], name='transaction_idempot_d892f2_idx')],
            },
        ),
    ]
